repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.5.1"
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
      - id: poetry-export
        args: ["--with=dev", "-o", "requirements.dev.txt"]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v1.7.0"
    hooks:
      - id: autopep8
